//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Andrew Engine 3.0.rc
//
#define IDI_MAIN_ICON                   101
#define IDD_DIALOG_SAVE                 113
#define IDD_OPEN_DIALOG                 114
#define IDD_DIALOG_TOOLBOX              115
#define IDD_DIALOG_ADD_OBJECT           116
#define IDD_DIALOG_USER_PREFERENCES     117
#define IDD_DIALOG_LIGHT_PROPERTIES     118
#define IDD_DIALOG_OBJECT_PROPERTIES    119
#define IDD_DIALOG_PARTICLE_PROPERTIES  120
#define IDD_DIALOG_BLUR_PROPERTIES      121
#define IDD_DIALOG_ANIM_PREFERENCES     122
#define IDD_DIALOG_ADD_ANIM_OBJECT      123
#define IDD_DIALOG_OBJECT_PHYSICS_PROPERTIES 124
#define IDD_DIALOG_LOADING              125
#define IDD_DIALOG_TERRAIN_MGR          127
#define IDD_DIALOG_WATER_SYSTEM_OPTIONS 128
#define IDD_DIALOG_GRAPHICS_PROPERTIES  129
#define IDC_CURSOR_TEST                 130
#define IDD_DIALOG_ADD_LIGHT            131
#define IDD_DIALOG_KINEMATICS           132
#define IDD_DIALOG_ADD_CONSTRAINT_HINGE 133
#define IDC_BUTTON_SD_ENTER             1001
#define IDC_BUTTON_SD_EXIT              1002
#define IDC_TEXT_BOX_SD_FILE_NAME       1003
#define IDC_TEXT_BOX_SD_LEVEL_NAME      1004
#define IDC_BUTTON_OD_OK                1005
#define IDC_BUTTON_OD_EXIT              1006
#define IDC_TEXT_BOX_OD_FILE_NAME       1007
#define IDC_BUTTON_TB_ADD_OBJECT        1008
#define IDC_BUTTON_TB_DELETE_SELECTED_OBJECT 1009
#define IDC_BUTTON_AO_ADD_OBJECT        1010
#define IDC_BUTTON_AO_EXIT              1011
#define IDC_EDIT_AO_OBJECT_NAME         1012
#define IDC_BUTTON_UP_SAVE              1013
#define IDC_BUTTON_UP_EXIT              1014
#define IDC_EDIT_UP_START_UP_LEVEL      1017
#define IDC_BUTTON_LP_EXIT              1018
#define IDC_EDIT_LP_LIGHT_RANGE         1019
#define IDC_EDIT_LP_POSITION            1021
#define IDC_EDIT_LP_POS_Y               1024
#define IDC_EDIT_LP_POS_Z               1025
#define IDC_BUTTON_TB_ADD_CUSTOM_OBJECT 1026
#define IDC_BUTTON_OP_OK                1029
#define IDC_BUTTON_OP_EXIT              1030
#define IDC_EDIT_OP_POS_X               1031
#define IDC_EDIT_OP_POS_Y               1032
#define IDC_EDIT_OP_POS_Z               1033
#define IDC_EDIT_OP_ROT_X               1034
#define IDC_EDIT_OP_ROT_Y               1035
#define IDC_EDIT_OP_ROT_Z               1036
#define IDC_EDIT_OP_SCALE               1037
#define IDC_EDIT_OP_TEXTURE_Z           1038
#define IDC_BUTTON_PP_OK                1039
#define IDC_EDIT_OP_TEXTURE_TZ          1039
#define IDC_BUTTON_PP_EXIT              1040
#define IDC_EDIT_PP_POS_X               1041
#define IDC_EDIT_PP_POS_Y               1042
#define IDC_EDIT_PP_POS_Z               1043
#define IDC_EDIT_PP_ROT_X               1044
#define IDC_EDIT_PP_TEXTURE_SIZE        1045
#define IDC_EDIT_PP_MAX_PARTICLES       1047
#define IDC_EDIT_PP_VEL                 1048
#define IDC_EDIT_PP_LIFE_SPAN           1049
#define IDC_EDIT_PP_X_MOD               1050
#define IDC_EDIT_PP_Y_MOD               1051
#define IDC_EDIT_PP_Z_MOD               1052
#define IDC_SLIDER_OP_OPACITY           1056
#define IDC_BUTTON_BP_OK                1057
#define IDC_BUTTON_BP_EXIT              1058
#define IDC_BUTTON_AP_OK                1059
#define IDC_BUTTON_AP_EXIT              1060
#define IDC_BUTTON_AP_ADD_OBJECT        1061
#define IDC_EDIT_AP_SELECTED_OBJECT     1062
#define IDC_EDIT_AP_RX                  1066
#define IDC_EDIT_AP_RY                  1067
#define IDC_EDIT_AP_RZ                  1068
#define IDC_EDIT_AP_X                   1069
#define IDC_EDIT_AP_Y                   1070
#define IDC_EDIT_AP_Z                   1071
#define IDC_EDIT_AP_S                   1072
#define IDC_EDIT_AP_TS                  1073
#define IDC_EDIT_AP_ANIM_SPEED          1074
#define IDC_BUTTON_AP_DELETE_OBJECT     1076
#define IDC_EDIT_AP_SX                  1077
#define IDC_EDIT_AP_SZ                  1078
#define IDC_BUTTON_AAO_OK               1079
#define IDC_BUTTON_AAO_EXIT             1080
#define IDC_EDIT_AAO_OBJECT_FILENAME    1081
#define IDC_EDIT_AAO_TEXTURE_DIRECTORY  1082
#define IDC_EDIT_AAO_ANIM_CLIP_NAME     1083
#define IDC_EDIT_AP_APH                 1084
#define IDC_COMBO_OPP_MATERIAL          1085
#define IDC_BUTTON_OPP_EXIT             1086
#define IDC_EDIT_OPP_GRAV_X             1087
#define IDC_EDIT_OPP_GRAV_Y             1088
#define IDC_EDIT_OPP_GRAV_Z             1089
#define IDC_EDIT_OPP_SPEC_GRAV          1090
#define IDC_PROGRESS_LOADING            1091
#define IDC_EDIT_OP_TEXTURE_Y           1092
#define IDC_EDIT_OP_TEXTURE_X           1093
#define IDC_EDIT_LP_ATT_X               1094
#define IDC_EDIT_OP_TEXTURE_TY          1094
#define IDC_EDIT_LP_ATT_Y               1095
#define IDC_EDIT_OP_TEXTURE_TX          1095
#define IDC_EDIT_LP_ATT_Z               1097
#define IDC_EDIT_LP_DIFF_X              1098
#define IDC_EDIT_LP_DIFF_Y              1099
#define IDC_EDIT_LP_DIFF_Z              1100
#define IDC_EDIT_OP_SCALE_Y             1101
#define IDC_EDIT_OP_SCALE_Z             1102
#define IDC_LOADING_MESSAGE             1103
#define IDC_CHECK_OP_REFLECTION         1104
#define IDC_EDIT_TM_TERRAIN_FRICT       1105
#define IDC_EDIT_TM_HEIGHTMAP_FILENAME  1106
#define IDC_EDIT_TM_BLENDMAP_FILENAME   1107
#define IDC_BUTTON_TM_OK                1108
#define IDC_BUTTON_WSO_OK               1109
#define IDC_EDIT_WSO_TOFR               1110
#define IDC_EDIT_WSO_X                  1111
#define IDC_EDIT_WSO_Y                  1112
#define IDC_EDIT_WSO_Z                  1113
#define IDC_EDIT_WSO_RX                 1114
#define IDC_EDIT_WSO_RY                 1115
#define IDC_EDIT_WSO_RZ                 1116
#define IDC_EDIT_WSO_WATER_TEX_TRANS_RATE 1117
#define IDC_EDIT_WSO_WATER_SCALE        1118
#define IDC_BUTTON_WSO_ADD_SYSTEM       1121
#define IDC_BUTTON_WSO_DELETE_SYSTEM    1122
#define IDC_EDIT_WSO_SCALE              1123
#define IDC_COMBO_OP_RENDER_TECH        1126
#define IDC_CHECK_WSO_USE_CIRCLE        1127
#define IDC_EDIT_WSO_SCALE_Z            1129
#define IDC_CHECK_USE_SKYMAP            1130
#define IDC_BUTTON_G_OK                 1131
#define IDC_EDIT_LP_LOOK_X              1132
#define IDC_EDIT_LP_LOOK_Y              1133
#define IDC_EDIT_LP_LOOK_Z              1134
#define IDC_EDIT_WSO_DIFF_AB            1135
#define IDC_EDIT_WSO_SPEC_AB            1136
#define IDC_EDIT_PP_EMIT_X              1137
#define IDC_EDIT_PP_EMIT_Y              1138
#define IDC_EDIT_PP_EMIT_Z              1139
#define IDC_BUTTON_PP_ADD_SYSTEM        1140
#define IDC_EDIT1                       1141
#define IDC_EDIT_PP_EMIT_TIME           1141
#define IDC_EDIT_LP_SPEC_X              1141
#define IDC_EDIT_K_TORQUE               1141
#define IDC_EDIT_HCO_AXIS_X             1141
#define IDC_EDIT_PP_PACCEL_X            1142
#define IDC_EDIT_PP_PACCEL_Y            1143
#define IDC_EDIT_PP_PACCEL_Z            1144
#define IDC_CHECK_FLASH_SEL             1145
#define IDC_BUTTON_PP_DELETE_SYSTEM     1146
#define IDC_BUTTON_AL_ADD_PL            1147
#define IDC_BUTTON_AL_ADD_SCPL          1148
#define IDC_EDIT_LP_SPEC_Y              1149
#define IDC_EDIT_LP_SPEC_Z              1150
#define IDC_EDIT_LP_AMBIENT_Y           1151
#define IDC_EDIT_LP_AMBIENT_Z           1152
#define IDC_EDIT_LP_AMBIENT_X           1153
#define IDC_BUTTON_K_OK                 1155
#define IDC_BUTTON_K_DELETE_CONSTRAINT  1156
#define IDC_EDIT_K_FORCE                1157
#define IDC_BUTTON_K_ADD_CONSTRAINT     1158
#define IDC_BUTTON_HCO_OK               1159
#define IDC_EDIT_HCO_AXIS_Y             1160
#define IDC_EDIT_HCO_AXIS_Z             1161
#define IDC_EDIT_HCO_AXIS_POS_X         1162
#define IDC_EDIT_HCO_AXIS_POS_Y         1163
#define IDC_EDIT_HCO_AXIS_POS_Z         1164
#define IDC_EDIT_HCO_LIMITS_X           1165
#define IDC_EDIT_HCO_LIMITS_Y           1166
#define IDC_EDIT_HCO_LIMITS_Z           1167
#define IDC_BUTTON_HCO_CANCEL           1169
#define IDC_EDIT_K_ANGL_VEL_X           1170
#define IDC_EDIT_K_ANGL_VEL_Y           1171
#define IDC_EDIT_K_ANGL_VEL_Z           1172
#define IDC_EDIT_K_LIN_X                1173
#define IDC_EDIT_K_LIN_Y                1174
#define IDC_EDIT_K_LIN_Z                1175
#define IDC_BUTTON_K_TOGGLE_PHYSICS     1176
#define IDC_BUTTON_K_EDIT_CONSTRAINT    1177
#define IDC_COMBO1                      1178
#define IDC_COMBO_PP_SYSTEM_TYPE        1178

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         40029
#define _APS_NEXT_CONTROL_VALUE         1179
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
